### ISSUE TITLE
Tunnelling.cs acquire other gameobjects

### ISSUE THREAD

**Issue by a962097364** [sigtrapgames/VrTunnellingPro-Unity#8]
Hello!
I want to get a value which is calculated by other scrpits on other gameobjects and use this value to add a new method to calculate fx value in TunnellingBase.cs. I tried to wirte some codes such as " public GameObject XXX" in Tunnelling.cs and TunnellingBase.cs. However there is no any place I can put the gameobject on the Inspector panel. How can I get the gameobject? 
Thank you.

**Comment by sigtrapgames** [comment]
I would recommend going the other way - set the force effect modes from another script, rather than modify the tunnelling script itself. VRTP uses entirely custom inspectors so there's no easy way to add a new field to the inspector (and from a software engineering perspective I'd recommend what I said above too, to keep your code modular).

However if that's definitely what you want to do, you'll have to modify VrTunnellingProEditorBase.cs to display your new field.

**Comment by a962097364** [comment]
> 

Thanks for your help, I will try it.
